package groupSPV.controller;

import java.io.File;
import java.io.PrintStream;

import org.bitcoinj.utils.BriefLogFormatter;

import groupSPV.model.CustomKit;
import groupSPV.view.LoginGUI;

/** BlockchainDriver is a driver class to initiate the downloading the Blockchain and display it.
 * @author Frank Fasola
 * @author James Donnell
 * @author Spencer Escalante
 * @author Trevor Silva */
public class BlockchainDriver {

	/** Default save location for any OS on a particular Bitcoin Network. */
	protected static String networkSaveLocation = getSystemPath() + "SeniorProject_Bitcoin_Client\\";
	
	protected static int currentNetwork;
	
	/** Default TestNet Folder. */
	private static final String testNetFolder = "test\\";

	/** Main method.
	 * @param args Argument stating "testnet" will use Bitcoin Test network. */
	public static void main(String[] args) {
		BriefLogFormatter.init(); // Sets logging format, default for now
		ignoreSELF4JErrors();

		currentNetwork = CustomKit.MAINNET;
		
		if (args.length > 0 && args[0].equals("testnet")) {
			System.out.println("TESTNET IN USE!!!");
			networkSaveLocation += testNetFolder;
			currentNetwork = CustomKit.TESTNET;
		}
		
		File tmpFile = new File(networkSaveLocation);
		if(!tmpFile.exists())
			tmpFile.mkdirs();
		
		new LoginGUI();
	}

	/** Returns User's full 'AppData' path if Windows, blank string if not.
	 *  @return 'AppData' full path. */
	private static String getSystemPath() {
		String appData = System.getenv("appdata");
		
		if (appData == null) return "";
		return appData + "\\";
	}
	
	/** Ignores errors related to "SELF4J" in System.err.
	 * These errors are generated by bitcoinj dependency that is unused. */
	private static void ignoreSELF4JErrors() {
		PrintStream filterOut = new PrintStream(System.err) {
			public void println(String l) {
				if (! l.startsWith("SLF4J") )
					super.println(l);
			}
		};
		System.setErr(filterOut);
	}
}